os: linux

dist: xenial

language: python

python:
  - "3.6"

git:
  depth: 10

cache: pip
install:
  - pip install -r requirements.txt

script: "make html"

deploy:
  strategy: git
  provider: pages
  local_dir: build/html/
  skip_cleanup: true
  token: $DOC_COCALC_TOKEN
  keep_history: false
  fqdn: doc.cocalc.com
  target_branch: gh-pages
  on:
    branch: master
